### ISSUE TITLE
Initial Project Plan

### ISSUE THREAD

**Issue by mmilutinovic1313** [LRNWebComponents/socket-project#1]
Hello, all - 

We have finished our first two writing assignments highlighting how we want to approach this project. Now comes the fun part...implementation! Below I will be adding a checklist for what we need to work on to complete this project. These tasks will include documentation, code, testing, and research. I will assign tasks to specific people as the project progresses, but everyone is allowed to help each other out with issues. Issues will grow as we run into bugs. Please report bugs that you see here and on the ELMS:LN GitHub repository (if they are not specific to just this project). If you have questions, please post them as issues so that our project can be transparent for our final paper and for Bryan's future reference. Here are the issues below: 

- [x] #2 Add ELMS:LN project to this repository.
- [x] #14 Add Testing Environment in DigitalOcean
- [x] #3 Research socket.io's API.
- [x] #13 Implement Basic Socket Server
- [x] #4 Search for socket.io module for Drupal. -- Optional
- [x] #5 Administrative Permissions
- [x] #6 Build / Edit socket.io module for Drupal. 
- [x] #7 Implement socket.io library and (or) module to socket-project ELMS:LN install.
- [x] #8 Work on custom chat implementation for ELMS:LN. - see #15 
- [x] #9 Document implementation process.
- [x] #10 Test solution.
- [x] #11 Prepare Pull-Request for ELMS:LN repository.
- [x] #12 Submit Pull-Request for approval.
- [x] #15 Web Components support for polymer (new ELMS:LN standard)
- [x] #16 Document Security for Paper

These are basic checkpoints that we should reach this semester. Other major issues that come up will be added here as well. Please submit pull-requests (PRs) for the issues in the following manner:

> #[issue-number] [description of issue] 

**Note: Please create branches after forking this repository for each issue you work on. This will allow for fewer merge conflicts in the future. The style will be: 

> i[issue-number] (optional short description)

This allows GitHub to tag PRs into the issue that they are trying to fix. Thank you all -- I can't wait to get started! :)
